services:
  php74: &php
    image: thecodingmachine/php:7.4-v4-cli-node14
    command: 'bash'
    volumes:
      - ./:/app
    user: ${MY_UID:-1000}
    tty: true
    working_dir: /app
    environment:
      XDEBUG_TRIGGER: "default_no_matter"
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: "client_host=${MY_IP:-172.17.0.1} discover_client_host=0 client_port=9000"
      PHP_IDE_CONFIG: "serverName=cli"
      PHP_EXTENSIONS: intl xdebug
  php80:
    <<: *php
    image: thecodingmachine/php:8.0-v4-cli-node14
  php81:
    <<: *php
    image: thecodingmachine/php:8.1-v4-cli-node14
  php82:
    <<: *php
    image: thecodingmachine/php:8.2-v4-cli-node14
  php83:
    <<: *php
    image: thecodingmachine/php:8.3-v4-cli-node14
